apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vulntracker.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vulntracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretsManager.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretsManager.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "vulntracker.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secretsManager.secretName }}
